---
- hosts: lab
  remote_user: centos
  sudo: yes
  tasks:
  - name: Install Apache.
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - httpd-devel
    notify:
      - Make sure Apache is started and configure it to run at boot
      - Open port 80

  handlers:
  - name: Make sure Apache is started and configure it to run at boot
    service: name=httpd state=started enabled=yes

  - name: Open port 80
    firewalld: service=http permanent=true state=enabled
